#!/bin/bash

echo "🔥 Firebase Setup for Proofreader Writer"
echo "========================================"
echo ""
echo "📋 Your Firebase project has been created:"
echo "   Project ID: proofreader-writer-1752894578"
echo "   Console: https://console.firebase.google.com/project/proofreader-writer-1752894578/"
echo ""
echo "✅ Completed:"
echo "   • Project created"
echo "   • Web app registered"
echo "   • Firebase config added to .env.local"
echo "   • Security rules files created"
echo ""
echo "🔧 Next steps (do these in Firebase Console):"
echo ""
echo "1. Enable Authentication:"
echo "   • Go to Authentication > Sign-in method"
echo "   • Enable Google provider"
echo "   • Add 'localhost' to authorized domains"
echo ""
echo "2. Create Firestore Database:"
echo "   • Go to Firestore Database"
echo "   • Click 'Create database'"
echo "   • Start in 'test mode'"
echo "   • Choose your region"
echo ""
echo "3. Enable Storage:"
echo "   • Go to Storage"
echo "   • Click 'Get started'"
echo "   • Start in 'test mode'"
echo "   • Choose same region as Firestore"
echo ""
echo "4. Create Service Account:"
echo "   • Go to Project settings > Service accounts"
echo "   • Click 'Generate new private key'"
echo "   • Download the JSON file"
echo ""
echo "After completing these steps, run:"
echo "   • chmod +x complete-firebase-setup.sh"
echo "   • ./complete-firebase-setup.sh [path-to-service-account.json]"
echo ""
echo "Or manually add to .env.local:"
echo "   FIREBASE_CLIENT_EMAIL=your-service-account-email"
echo '   FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nYour-Key\n-----END PRIVATE KEY-----"' 